import Head from "next/head"
import Link from "next/link"

import { BsLinkedin, BsGithub, BsInstagram } from "react-icons/bs"

export default function Home() {
  return (
    <>
      <Head>
        <title>Mayank Gupta</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <!-- ======= Header ======= --> */}
      <header id="header">
        <div className="container">
          <h1>
            <Link href="/">Mayank Gupta</Link>
          </h1>
          {/* <!-- Uncomment below if you prefer to use an image logo --> */}
          {/* <!-- <a href="index.html" className="mr-auto"><img src="assets/img/logo.png" alt="" className="img-fluid"></a> --> */}
          <h2>
            I"m a passionate <span>Software Developer</span> from Canada
          </h2>

          <nav id="navbar" className="navbar">
            <ul>
              <li>
                <Link className="nav-link active" href="/">
                  Home
                </Link>
              </li>
              <li>
                <Link className="nav-link" href="/about">
                  About
                </Link>
              </li>
              <li>
                <Link className="nav-link" href="/resume">
                  Resume
                </Link>
              </li>
              <li>
                <Link className="nav-link" href="/contact">
                  Contact
                </Link>
              </li>
            </ul>
            <i className="bi bi-list mobile-nav-toggle"></i>
          </nav>
          {/* <!-- .navbar --> */}

          <div className="social-links">
            <Link href="#" className="linkedin">
              <BsLinkedin />
            </Link>
            <Link href="#" className="github">
              <BsGithub />
            </Link>
            <Link href="#" className="instagram ">
              <BsInstagram />
            </Link>
          </div>
        </div>
      </header>
      {/* <!-- End Header --> */}
    </>
  )
}
