import Head from "next/head"
import Link from "next/link"
import links from "../links.json"

import { BsLinkedin, BsGithub, BsInstagram } from "react-icons/bs"
import { FaGooglePlay } from "react-icons/fa"

export default function Home() {
  return (
    <>
      <Head>
        <title>Mayank Gupta</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <!-- ======= Header ======= --> */}
      <header id="header">
        <div className="container">
          <h1>
            <Link href="/">Mayank Gupta</Link>
          </h1>
          {/* <!-- Uncomment below if you prefer to use an image logo --> */}

          <h2>
            I"m a passionate <span>Software Developer</span> from Canada
          </h2>

          <nav id="navbar" className="navbar">
            <ul>
              <li>
                <Link className="nav-link active" href="/">
                  Home
                </Link>
              </li>
              <li>
                <Link className="nav-link" href="/about">
                  About Me
                </Link>
              </li>
              <li>
                <Link className="nav-link" href="/resume">
                  Resume
                </Link>
              </li>
              <li>
                <Link className="nav-link" href="/projects">
                  Projects
                </Link>
              </li>
              <li>
                <Link className="nav-link" href="/contact">
                  Contact Me
                </Link>
              </li>
            </ul>
            <i className="bi bi-list mobile-nav-toggle"></i>
          </nav>
          {/* <!-- .navbar --> */}

          <div className="social-links">
            <Link href={links.linkedin} className="linkedin">
              <BsLinkedin />
            </Link>
            <Link href={links.github} className="github">
              <BsGithub />
            </Link>
            <Link href={links.instagram} className="instagram ">
              <BsInstagram />
            </Link>
            <Link href={links.playStore} className="instagram ">
              <FaGooglePlay />
            </Link>
          </div>
        </div>
      </header>
      {/* <!-- End Header --> */}
    </>
  )
}
